Repository Pre-HotSix/wanted-pre-onboarding-imlab, pull requests merged in 2022-09, with the labels that each got.

#4 Feature: [#1] 공통 컴포넌트 구성
  config/webpack.common.js
  package-lock.json
  package.json
  src/assets/banner.png
  src/assets/no_image.png
  src/assets/svgs/star-icon.svg
  src/components/Card/index.tsx
  src/components/Card/style.ts
  src/components/CardContainer/index.tsx
  src/components/CardContainer/style.ts
  src/components/Container/index.tsx
  src/components/Container/style.ts
  src/components/PageTitle/index.tsx
  src/components/PageTitle/style.ts
  src/components/commons/layout/Sidebar/index.tsx
  src/components/index.ts
  src/pages/DetailPage/components/Card/index.tsx
  src/pages/DetailPage/components/Card/style.ts
  src/pages/DetailPage/components/DetailContainer/index.tsx
  src/pages/DetailPage/components/DetailContainer/style.ts
  src/pages/DetailPage/components/ExplainContainer/index.tsx
  src/pages/DetailPage/components/ExplainContainer/style.ts
  src/pages/DetailPage/components/index.ts
  src/pages/DetailPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/HomePage/style.ts
  src/pages/Main/index.tsx
  src/pages/NowPlayingPage/index.tsx
  src/pages/SearchMoviePage/index.tsx
  src/pages/TopRatedPage/index.tsx
  src/pages/UpComingPage/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  yarn.lock
Labels: enhancement

#9 [#5] Feat : 공용 사용 api 함수 정리, CSS 다듬기 , 검색 로직
  public/index.html
  src/apis/index.ts
  src/components/Card/index.tsx
  src/components/commons/layout/Header/index.tsx
  src/components/commons/layout/Header/style.ts
  src/components/commons/layout/Sidebar/index.tsx
  src/components/commons/layout/Sidebar/style.ts
  src/pages/HomePage/index.tsx
  src/pages/SearchMoviePage/index.tsx
Labels: enhancement

#13 ✨ Feat : 검색 페이지 무한 스크롤 적용 및 무한 스크롤 훅 추상화
  package-lock.json
  package.json
  src/apis/index.ts
  src/components/Card/index.tsx
  src/hooks/useInfiQry.tsx
  src/pages/SearchMoviePage/index.tsx
Labels: enhancement

#17 🐛 [#16] Fix : input 재적용해도 refetch 되도록 useEffect 훅 적용
  src/hooks/useInfiQry.tsx
  src/pages/SearchMoviePage/index.tsx
Labels: bug, modify

#27 Fix: [#26] 불필요한 폴더 및 스타일 삭제
  src/pages/Main/index.tsx
  src/routes/index.tsx
Labels: bug
